id = "rose-pine-blur"
name = "Rose Pine Blur"
schema_version = 1
version = "1.0.0"
authors = ["Sataros221 (Javier Valdés González) <sataros221@gmail.com>"]
description = "Rose Pine themes with blur"
repository = "https://github.com/sataros221/zed-rose-pine-blur"
